# Generated by Django 4.2.5 on 2023-10-15 14:26

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_name', models.CharField(max_length=200)),
                ('flavours', models.CharField(choices=[('chocolate', 'chocolate'), ('black forest', 'black forest'), ('red velvet', 'red velvet'), ('butter  scotch', 'butter scotch'), ('vanilla', 'vanilla'), ('pineapple', 'pineapple'), ('dates', 'dates'), ('non-alcoholic', 'non-alcoholic'), ('dry-fruits', 'dry-fruits'), ('mixed-fruits', 'mixed-fruits'), ('blueberry', 'blueberry'), ('strawberry', 'strawberry')], default='chocolate', max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='CakeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CakeVarients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_price', models.PositiveIntegerField()),
                ('weight', models.CharField(choices=[('0.5 kg', '0.5 kg'), ('1 kg', '1 kg'), ('2 kg', '2 kg'), ('3 kg', '3 kg'), ('4 kg', '4 kg'), ('5 kg', '5 kg')], default='0.5 kg', max_length=200)),
                ('cake_type', models.CharField(choices=[('egg', 'egg'), ('egg-less', 'egg-less')], default='egg', max_length=200)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakehouse.cake')),
            ],
        ),
        migrations.CreateModel(
            name='CakeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=200)),
                ('cake_varient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakehouse.cakevarients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CakeOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order-placed', 'order-placed'), ('cancelled', 'cancelled'), ('packed', 'packed'), ('in-transit', 'in-transit'), ('delivered', 'delivered')], default='order-placed', max_length=200)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('expected_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('cake_varient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakehouse.cakevarients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CakeOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_price', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('cake_varient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakehouse.cakevarients')),
            ],
        ),
        migrations.CreateModel(
            name='CakeCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in-cart', 'in-cart'), ('order-placed', 'order-placed'), ('cancelled', 'cancelled')], default='in-cart', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cake_varient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakehouse.cakevarients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cake',
            name='cat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakehouse.cakecategory'),
        ),
    ]
