# Generated by Django 4.2.6 on 2023-11-24 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakehouse', '0002_alter_cakeorders_expected_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakereview',
            name='cake_varient',
        ),
        migrations.AddField(
            model_name='cakereview',
            name='cake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakehouse.cake'),
        ),
    ]
